#!/bin/sh

# can be either 'net', 'nor' or 'nand''
kernel=net
root=net

uimage=uImage-333
jffs2=root-pcm043.jffs2



autoboot_timeout=3

bootargs="console=ttymxc0,115200 noinitrd mtdparts=spi0.0:512k(barebox),4560k(kernel),16256k@128k(firmware) vt.global_cursor_default=0 root=/dev/mtdblock2"

# use 'dhcp' to do dhcp in barebox and in kernel
#ip=dhcp

# or set your networking parameters here
eth0.ipaddr=192.168.0.102
eth0.netmask=255.255.255.0
#eth0.gateway=a.b.c.d
eth0.serverip=192.168.0.78
eth0.ethaddr=00:50:c2:8c:e6:0e
